"""
crvae_model/utils/data_utils.py
Everything the surrogate-training stage needs to turn a generator .npz into
windows: loading the trajectory + its ground-truth causal graph, and the
chronological train/val/test split + windowing.

This is the training-side counterpart of utils/data_utils.py at the project
root, which serves the attack stage (it additionally has parent/non-parent/
random channel masks and a checkpoint loader -- attack-only concerns that
have no reason to live inside crvae_model). The loading/windowing functions
below are intentionally duplicated between the two rather than shared: only
data/ itself -- the .npz files and their generators -- is common ground
between training and attack; see crvae_model/train.py's module docstring.

Two things differ from TimeCAT_new's original utils.py/data_prep.ipynb:
  - utils.py's getCausalMatrix (a hardcoded per-dataset dict) is gone. Every
    data/<name>_gen.py now writes its ground-truth graph straight into the
    dataset's own .npz (key "A"), generated once, in one place --
    load_ground_truth below just reads it back.
  - utils.py's preprocessSyn (window everything with a fixed context, then
    split 80/20) is replaced by create_split_windows: it splits the raw
    trajectory itself chronologically first (train earliest, then val, then
    test) and windows each piece independently, so no window straddles two
    splits -- windowing before splitting scatters near-duplicate, heavily
    overlapping windows (stride-1 sliding windows only differ by one
    timestep) across the split boundary and leaks information between them.
    It also adds a third, held-out test split that no trial trains or
    selects on (the original pipeline only ever produced train/val).
"""

from __future__ import annotations

import json

import numpy as np


# --------------------------------------------------------------------------- #
# Loading a generator artifact
# --------------------------------------------------------------------------- #
def load_trajectory(npz_path, version="std"):
    """Loads the trajectory produced by data/<name>_gen.py plus its meta dict.

    `version` selects which array to load, matching the two variants every
    data/<name>_gen.py writes to the .npz:
      - "std" (default): X_std, the standardized (zero-mean, unit-variance)
        trajectory [T, D].
      - "raw": X_raw, the original trajectory [T, D] as generated by the
        map/ODE/SCM, before any rescaling.
    """
    key = {"std": "X_std", "raw": "X_raw"}.get(version)
    if key is None:
        raise ValueError(f"unknown data version {version!r}; expected one of ['std', 'raw']")
    d = np.load(npz_path, allow_pickle=True)
    X = np.asarray(d[key], dtype=np.float32)
    meta = json.loads(str(d["meta"]))
    return X, meta


def load_ground_truth(npz_path):
    """Ground-truth causal adjacency A written by data/<name>_gen.py
    alongside the trajectory: A[i, j] == 1 means j is a parent of i, [D, D].
    Same convention cLSTM's causal_graph argument expects."""
    d = np.load(npz_path, allow_pickle=True)
    return np.asarray(d["A"], dtype=np.float64)


# --------------------------------------------------------------------------- #
# Chronological split + windowing
# --------------------------------------------------------------------------- #
def create_split_windows(X, context, val_frac, test_frac, verbose=True, logger=None):
    """Chronological train/val/test split of the trajectory, then windowing
    (sliding, stride 1, window length `context`) within each split
    independently.

    val_frac and test_frac are each a fraction of the trajectory's total
    length T (not of the window count); train gets whatever time remains,
    and comes first chronologically, then val, then test:

        n_test  = int(T * test_frac)
        n_val   = int(T * val_frac)
        n_train = T - n_val - n_test
        train, val, test = X[:n_train], X[n_train:n_train+n_val], X[n_train+n_val:]

    Returns (X_train, X_val, X_test), each a list of whole windows -- split
    each window into (history, target) with split_window below, right where
    it is fed to the model, instead of carrying two arrays in lockstep.
    """
    if context < 2:
        raise ValueError("Context value should have minimum length = 2.")

    T = len(X)
    n_test = int(T * test_frac)
    n_val = int(T * val_frac)
    n_train = T - n_val - n_test
    segments = [
        ("train", X[:n_train]),
        ("val", X[n_train:n_train + n_val]),
        ("test", X[n_train + n_val:]),
    ]

    log = logger.info if logger is not None else (lambda m: print(m, flush=True))
    if verbose:
        log("Complete!")

    out = {}
    for name, seg in segments:
        seg = seg.tolist() if isinstance(seg, np.ndarray) else seg
        if context > len(seg):
            raise ValueError(
                f"Context value cannot exceed the {name} split's length ({len(seg)} of T={T}); "
                f"retry with a smaller context, or a smaller val_frac/test_frac."
            )
        out[name] = [seg[i: i + context] for i in range(len(seg) - context + 1)]
        log(f"{name} windows : {len(out[name]), len(out[name][0]), len(out[name][0][0])}")

    return out["train"], out["val"], out["test"]


def split_window(window):
    """A whole (context, D) window -> (X_left, X_right): everything but the
    last step is what the encoder sees, and the last step (kept as a
    (1, D) block, not squeezed) is the one-step-ahead forecast target cLSTM
    expects as X_right (forward(X_left, future=X_right.shape[1]))."""
    return window[:-1], window[-1:]
