"""
utils/data_utils.py
Everything the attack stage needs that touches a generator .npz file, turns
a trajectory into windows for the cLSTM surrogate, or rebuilds a trained
surrogate from its checkpoint.

load_trajectory / load_ground_truth / create_split_windows / split_window
are intentionally byte-for-byte the same as crvae_model/utils/data_utils.py's
copies (used by training) rather than imported from there -- see this
project's utils/common.py module docstring on why crvae_model/ and this
package never share Python code, only data/ and a checkpoint.pt file. The
one thing genuinely specific to attacking (not training) a surrogate lives
only here: load_model, which reconstructs a frozen cLSTM straight from a
saved checkpoint.pt -- the sole place this package reaches into
crvae_model (crvae_model.model.cLSTM, the class itself, not
crvae_model.train or crvae_model.utils).

Ported and consolidated from three places in TimeCAT_new:
  - utils.py's getCausalMatrix (a hardcoded per-dataset dict, duplicated
    verbatim into data_prep.ipynb so the same graph could be reconstructed
    at data-generation time) is gone. Every data/<name>_gen.py now writes
    its ground-truth graph straight into the dataset's own .npz (key "A"),
    generated once, in one place -- load_ground_truth below just reads it
    back. That removes the two-copies-that-can-drift risk the original
    getCausalMatrix had (one copy in utils.py, called from three different
    training/attack/notebook contexts).
  - utils.py's preprocessSyn (window everything with a fixed context, then
    split 80/20) is replaced by create_split_windows, ported from
    codebase_caufrts's utils/data_utils.py: it splits the raw trajectory
    itself chronologically first (train earliest, then val, then test) and
    windows each piece independently, so no window straddles two splits --
    windowing before splitting scatters near-duplicate, heavily overlapping
    windows (stride-1 sliding windows only differ by one timestep) across
    the split boundary and leaks information between them. It also adds a
    third, held-out test split that no trial trains or selects on (the
    original pipeline only ever produced train/val).
  - utils.py's load_model (needed a `metadata` dict *and* a `dataset_name`
    string passed in separately, just so it could call getCausalMatrix again
    to rebuild the architecture) is replaced by a version that reads the
    causal graph straight out of the checkpoint's own saved hyperparameters
    (see crvae_model.model.cLSTM's docstring on why causal_graph is part of
    the model's hyperparameters, not an inference-time extra) -- one
    self-contained argument (the checkpoint path) instead of three.
  - helpers.py's get_parent_mask / get_nonparent_mask / get_random_mask move
    here unchanged: they are data/graph utilities, not attack logic, but
    they are only ever used to decide which channels an attack may perturb,
    so they belong on the attack side, not inside crvae_model.
"""

from __future__ import annotations

import json

import numpy as np
import torch

from crvae_model.model import cLSTM


# --------------------------------------------------------------------------- #
# Loading a generator artifact
# --------------------------------------------------------------------------- #
def load_trajectory(npz_path, version="std"):
    """Loads the trajectory produced by data/<name>_gen.py plus its meta dict.

    `version` selects which array to load, matching the two variants every
    data/<name>_gen.py writes to the .npz:
      - "std" (default): X_std, the standardized (zero-mean, unit-variance)
        trajectory [T, D].
      - "raw": X_raw, the original trajectory [T, D] as generated by the
        map/ODE/SCM, before any rescaling.
    """
    key = {"std": "X_std", "raw": "X_raw"}.get(version)
    if key is None:
        raise ValueError(f"unknown data version {version!r}; expected one of ['std', 'raw']")
    d = np.load(npz_path, allow_pickle=True)
    X = np.asarray(d[key], dtype=np.float32)
    meta = json.loads(str(d["meta"]))
    return X, meta


def load_ground_truth(npz_path):
    """Ground-truth causal adjacency A written by data/<name>_gen.py
    alongside the trajectory: A[i, j] == 1 means j is a parent of i, [D, D].
    Same convention cLSTM's causal_graph argument expects."""
    d = np.load(npz_path, allow_pickle=True)
    return np.asarray(d["A"], dtype=np.float64)


# --------------------------------------------------------------------------- #
# Chronological split + windowing
# --------------------------------------------------------------------------- #
def create_split_windows(X, context, val_frac, test_frac, verbose=True, logger=None):
    """Chronological train/val/test split of the trajectory, then windowing
    (sliding, stride 1, window length `context`) within each split
    independently.

    val_frac and test_frac are each a fraction of the trajectory's total
    length T (not of the window count); train gets whatever time remains,
    and comes first chronologically, then val, then test:

        n_test  = int(T * test_frac)
        n_val   = int(T * val_frac)
        n_train = T - n_val - n_test
        train, val, test = X[:n_train], X[n_train:n_train+n_val], X[n_train+n_val:]

    Returns (X_train, X_val, X_test), each a list of whole windows -- split
    each window into (history, target) with split_window below, right where
    it is fed to the model, instead of carrying two arrays in lockstep.
    """
    if context < 2:
        raise ValueError("Context value should have minimum length = 2.")

    T = len(X)
    n_test = int(T * test_frac)
    n_val = int(T * val_frac)
    n_train = T - n_val - n_test
    segments = [
        ("train", X[:n_train]),
        ("val", X[n_train:n_train + n_val]),
        ("test", X[n_train + n_val:]),
    ]

    log = logger.info if logger is not None else (lambda m: print(m, flush=True))
    if verbose:
        log("Complete!")

    out = {}
    for name, seg in segments:
        seg = seg.tolist() if isinstance(seg, np.ndarray) else seg
        if context > len(seg):
            raise ValueError(
                f"Context value cannot exceed the {name} split's length ({len(seg)} of T={T}); "
                f"retry with a smaller context, or a smaller val_frac/test_frac."
            )
        out[name] = [seg[i: i + context] for i in range(len(seg) - context + 1)]
        log(f"{name} windows : {len(out[name]), len(out[name][0]), len(out[name][0][0])}")

    return out["train"], out["val"], out["test"]


def split_window(window):
    """A whole (context, D) window -> (X_left, X_right): everything but the
    last step is what the encoder sees, and the last step (kept as a
    (1, D) block, not squeezed) is the one-step-ahead forecast target cLSTM
    expects as X_right (forward(X_left, future=X_right.shape[1]))."""
    return window[:-1], window[-1:]


# --------------------------------------------------------------------------- #
# Causal-graph masks (used to pick which channels an attack is allowed to
# perturb: only channel j's parents, only its non-parents, or a random set).
# --------------------------------------------------------------------------- #
def get_parent_mask(causal_graph, target_dim):
    """Boolean mask of parent channels for target_dim j: P_j = {k : A[j,k]=1}
    (row j of the adjacency matrix)."""
    mask = causal_graph[target_dim] != 0
    return mask.astype(bool)


def get_nonparent_mask(causal_graph, target_dim):
    """Boolean mask of non-parent, non-target channels: k not in P_j and
    k != j."""
    parent_mask = get_parent_mask(causal_graph, target_dim)
    nonparent_mask = ~parent_mask
    nonparent_mask[target_dim] = False
    return nonparent_mask


def get_random_mask(n_dim, n_select, exclude_dim=None, seed=None):
    """Boolean mask selecting n_select random channels, optionally excluding
    a specific dimension (the target) from the selection pool."""
    rng = np.random.RandomState(seed) if seed is not None else np.random.RandomState()

    candidates = list(range(n_dim))
    if exclude_dim is not None:
        candidates.remove(exclude_dim)

    n_select = min(n_select, len(candidates))
    chosen = rng.choice(candidates, size=n_select, replace=False)

    mask = np.zeros(n_dim, dtype=bool)
    mask[chosen] = True
    return mask


# --------------------------------------------------------------------------- #
# Rebuilding a trained surrogate from its checkpoint
# --------------------------------------------------------------------------- #
def load_model(checkpoint_path, device) -> cLSTM:
    """Rebuild a frozen, eval-mode cLSTM straight from a checkpoint saved by
    crvae_model.utils.common.save_checkpoint -- self-contained (n_dim,
    hidden_size, and the causal_graph itself all travel with the
    checkpoint), so no separate dataset name or metadata file, and no code
    from crvae_model.train, is needed to reconstruct the architecture --
    just the checkpoint file plus crvae_model.model.cLSTM's class
    definition."""
    ckpt = torch.load(checkpoint_path, map_location=device)
    hp = ckpt["model_hp"]
    model = cLSTM(
        n_dim=hp["n_dim"], hidden_size=hp["hidden_size"],
        causal_graph=np.asarray(hp["causal_graph"]),
    ).to(device)
    model.load_state_dict(ckpt["state_dict"])
    model.eval()
    for p in model.parameters():
        p.requires_grad_(False)
    return model
